---
ACTIVE_CLIENT: 3
BATCH_SIZE: 64
CLIENT_EPOCHS: 2
DEVICE: cpu
LOG_LEVEL: 20
LR: 0.1
NUM_CLIENT: 100
NUM_PROCESS: 4
OPTIM:
  LR: 0.1
  MOMENTUM: 0.9
  NAME: SGD
SERVER_EPOCHS: 20
WB_ENTITY: example_entity
WB_PROJECT: example_project
